version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: syns2023
    container_name: al-folio-website
    command: bash -c "
      rm -f Gemfile.lock
      && bundler exec jekyll serve --watch --host=0.0.0.0 --livereload --verbose --trace --force_polling"
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll